version: '3.8'

networks:
  private:
    name: private

services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - private
    
  server:
    container_name: server
    image: server
    build: .
    restart: always
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db
    networks:
      - private
