version: '3.8'

networks:
  private:
    name: private
    external: true

services:
  frontend:
    container_name: frontend
    image: frontend
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
      - private
  